version: "3.7"
services:
  api:
    image: "bhub:challenge"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    volumes:
      - .:/app/src
    ports:
      - "8082:8080"
    environment:
      PROJECT_SERVICE_TYPE: "api"
  dev_container:
    image: "bhub:challenge"
    build: .
    ports:
      - "8081:8080"
    command: "tail -f /dev/null"
    entrypoint: "./entrypoint-dev.sh"
    volumes:
      - .:/app/src
    env_file:
      - .env
    depends_on:
      - db
      - cache
    environment:
      PROJECT_SERVICE_TYPE: "dev_container"
  cache:
    image: memcached:1.6-alpine
    ports:
      - '11212:11211'
  db:
    image: "postgres:12"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
