# Generated by Django 4.0.5 on 2022-06-10 14:15

import core.helpers.validators.cell_phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customeraddress_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell_phone',
            field=models.CharField(max_length=20, validators=[core.helpers.validators.cell_phone.validate_cell_phone]),
        ),
    ]
