# Generated by Django 4.0.5 on 2022-06-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at'], 'verbose_name': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['created_at'], 'verbose_name': 'Bank'},
        ),
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'ordering': ['created_at'], 'verbose_name': 'Customer Account'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['created_at'], 'verbose_name': 'Customer Address'},
        ),
    ]
