# Generated by Django 4.0.5 on 2022-06-10 19:34

import core.helpers.validators.zip_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_address_options_alter_bank_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[core.helpers.validators.zip_code.validate_zip_code]),
        ),
    ]
