# Generated by Django 4.0.5 on 2022-06-10 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0010_alter_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
