# Generated by Django 4.0.5 on 2022-06-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_blocked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='valid_country',
        ),
    ]
