# Generated by Django 4.0.5 on 2022-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_bank_valid_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
