# Generated by Django 4.0.5 on 2022-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customeraccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='direct_transfer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='token_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
