name: publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'semantic-release') && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install Semantic Release
        run: |
          python3 -m pip install python-semantic-release==7.27.1
          semantic-release --help
      - name: Publish
        run: |
          git config --global user.name "megalus"
          git config --global user.email "chrismaille@megalus.com.br"
          semantic-release publish
